"""
Tech stack fingerprint signatures.
Each entry maps a technology to detection rules across headers, cookies, HTML, scripts, meta tags, etc.
"""

import re
from re import Pattern
from typing import Any

from fingerprints.extended_catalog import EXTENDED_SIGNATURES
from fingerprints.web_server_catalog import WEB_SERVER_SIGNATURES

SIGNATURES = {'Apache': {'headers': {'Server': 'Apache(?:/(\\d+[\\d.]+))?'}, 'category': 'Web Server'},
 'Nginx': {'headers': {'Server': 'nginx(?:/(\\d+[\\d.]+))?'}, 'category': 'Web Server'},
 'IIS': {'headers': {'Server': 'Microsoft-IIS(?:/(\\d+[\\d.]+))?'}, 'category': 'Web Server'},
 'LiteSpeed': {'headers': {'Server': 'LiteSpeed'}, 'category': 'Web Server'},
 'Caddy': {'headers': {'Server': 'Caddy'}, 'category': 'Reverse Proxy', 'html': ['caddy', 'caddyserver']},
 'OpenResty': {'headers': {'Server': 'openresty(?:/(\\d+[\\d.]+))?'}, 'category': 'Web Server'},
 'Gunicorn': {'headers': {'Server': 'gunicorn(?:/(\\d+[\\d.]+))?'}, 'category': 'Web Server'},
 'Werkzeug': {'headers': {'Server': 'Werkzeug(?:/(\\d+[\\d.]+))?'}, 'category': 'Web Server'},
 'Tornado': {'headers': {'Server': 'TornadoServer(?:/(\\d+[\\d.]+))?'}, 'category': 'Web Server'},
 'PHP': {'headers': {'X-Powered-By': 'PHP(?:/(\\d+[\\d.]+))?'}, 'cookies': ['PHPSESSID'], 'category': 'Language'},
 'ASP.NET': {'headers': {'X-Powered-By': 'ASP\\.NET', 'X-AspNet-Version': '(\\d+[\\d.]+)'},
             'cookies': ['ASP\\.NET_SessionId'],
             'category': 'Language'},
 'Node.js': {'headers': {'X-Powered-By': 'Express'}, 'category': 'Language'},
 'Ruby on Rails': {'headers': {'X-Powered-By': 'Phusion Passenger(?:/(\\d+[\\d.]+))?'},
                   'cookies': ['_session_id'],
                   'html': ['content="Ruby on Rails'],
                   'category': 'Framework'},
 'Python': {'headers': {'X-Powered-By': 'Python(?:/(\\d+[\\d.]+))?'}, 'category': 'Language'},
 'Laravel': {'cookies': ['laravel_session', 'XSRF-TOKEN'],
             'html': ['csrf-token.*laravel', 'Laravel'],
             'category': 'Framework'},
 'CakePHP': {'html': ['cakephp', 'CakePHP'], 'category': 'Framework'},
 'Yii': {'html': ['Yii Framework', 'yiiframework'], 'category': 'Framework'},
 'Zend Framework': {'html': ['Zend Framework', 'zf2'], 'category': 'Framework'},
 'FuelPHP': {'html': ['FuelPHP', 'fuelphp'], 'category': 'Framework'},
 'Slim Framework': {'html': ['Slim Framework', 'slim'], 'category': 'Framework'},
 'Hapi.js': {'html': ['hapi', 'hapi.js'], 'category': 'Framework'},
 'Koa': {'html': ['koa', 'Koa'], 'category': 'Framework'},
 'NestJS': {'html': ['nestjs', '@nestjs'], 'category': 'Framework'},
 'AdonisJS': {'html': ['adonis', 'adonisjs'], 'category': 'Framework'},
 'Nuxt.js': {'html': ['__NUXT__', '/_nuxt/'], 'category': 'JS Framework'},
 'Svelte': {'html': ['svelte-', '__svelte'], 'category': 'JS Framework'},
 'Preact': {'html': ['preact', 'preactjs'], 'category': 'JS Framework'},
 'Alpine.js': {'html': ['alpinejs', 'x-data'], 'category': 'JS Framework'},
 'Mithril': {'html': ['mithril', 'mithril.js'], 'category': 'JS Framework'},
 'Ember.js': {'html': ['ember', 'ember.js'], 'category': 'JS Framework'},
 'Backbone.js': {'html': ['backbone', 'backbone.js'], 'category': 'JS Framework'},
 'Knockout.js': {'html': ['knockout', 'knockoutjs'], 'category': 'JS Framework'},
 'Aurelia': {'html': ['aurelia', 'aurelia.io'], 'category': 'JS Framework'},
 'Dojo': {'html': ['dojo', 'dojo.js'], 'category': 'JS Framework'},
 'Django': {'cookies': ['csrftoken', 'sessionid'], 'html': ['csrfmiddlewaretoken'], 'category': 'Framework'},
 'Flask': {'cookies': ['session'], 'headers': {'Server': 'Werkzeug'}, 'category': 'Framework'},
 'Express.js': {'headers': {'X-Powered-By': 'Express'}, 'category': 'Framework'},
 'FastAPI': {'html': ['fastapi', '/openapi\\.json', '/docs'],
             'paths': ['/openapi\\.(?:json|yaml)', '/docs(?:/.*)?', '/redoc(?:/.*)?'],
             'category': 'Framework'},
 'GraphQL': {'html': ['graphql', '__schema'],
             'paths': ['/graphql(?:/.*)?', '/graphiql(?:/.*)?', '/graphql-ws(?:/.*)?'],
             'category': 'API'},
 'Swagger UI': {'html': ['swagger-ui', 'swagger'],
                'paths': ['/swagger(?:-ui)?(?:/.*)?', '/docs(?:/.*)?', '/redoc(?:/.*)?'],
                'category': 'API Docs'},
 'OpenAPI': {'html': ['openapi', 'OpenAPI'],
             'paths': ['/openapi\\.(?:json|yaml)', '/openapi(?:/.*)?'],
             'category': 'API Docs'},
 'Spring': {'cookies': ['JSESSIONID'], 'headers': {'X-Application-Context': '.+'}, 'category': 'Framework'},
 'Symfony': {'cookies': ['PHPSESSID'], 'html': ['Symfony', 'sf_redirect'], 'category': 'Framework'},
 'CodeIgniter': {'cookies': ['ci_session'], 'html': ['CodeIgniter'], 'category': 'Framework'},
 'WordPress': {'html': ['/wp-content/', '/wp-includes/', 'wordpress'],
               'meta': {'generator': 'WordPress(?:\\s(\\d+[\\d.]+))?'},
               'category': 'CMS'},
 'Elementor': {'html': ['/wp-content/plugins/elementor/', 'elementor'], 'category': 'WordPress Plugin'},
 'WooCommerce': {'html': ['/wp-content/plugins/woocommerce/', 'woocommerce'], 'category': 'CMS / E-Commerce'},
 'Yoast SEO': {'html': ['/wp-content/plugins/wordpress-seo/', 'yoast'], 'category': 'WordPress Plugin'},
 'Contact Form 7': {'html': ['/wp-content/plugins/contact-form-7/', 'contact-form-7'], 'category': 'WordPress Plugin'},
 'WPForms': {'html': ['/wp-content/plugins/wpforms-lite/', 'wpforms'], 'category': 'WordPress Plugin'},
 'WP Rocket': {'html': ['/wp-content/plugins/wp-rocket/', 'wp-rocket'], 'category': 'WordPress Plugin'},
 'LiteSpeed Cache': {'html': ['/wp-content/plugins/litespeed-cache/', 'litespeed-cache'],
                     'category': 'WordPress Plugin'},
 'All in One SEO': {'html': ['/wp-content/plugins/all-in-one-seo-pack/', 'aioseo'], 'category': 'WordPress Plugin'},
 'WPBakery': {'html': ['/wp-content/plugins/js_composer/', 'wpbakery'], 'category': 'WordPress Plugin'},
 'Divi': {'html': ['/wp-content/themes/divi/', 'divi'], 'category': 'WordPress Theme'},
 'Avada': {'html': ['/wp-content/themes/avada/', 'avada'], 'category': 'WordPress Theme'},
 'GeneratePress': {'html': ['/wp-content/themes/generatepress/', 'generatepress'], 'category': 'WordPress Theme'},
 'WP Super Cache': {'html': ['/wp-content/plugins/wp-super-cache/', 'wpsupercache'], 'category': 'WordPress Plugin'},
 'WP Mail SMTP': {'html': ['/wp-content/plugins/wp-mail-smtp/', 'wpmailsmtp'], 'category': 'WordPress Plugin'},
 'UpdraftPlus': {'html': ['/wp-content/plugins/updraftplus/', 'updraftplus'], 'category': 'WordPress Plugin'},
 'Really Simple SSL': {'html': ['/wp-content/plugins/really-simple-ssl/', 'really-simple-ssl'],
                       'category': 'WordPress Plugin'},
 'SiteOrigin': {'html': ['/wp-content/plugins/siteorigin-panels/', 'siteorigin'], 'category': 'WordPress Plugin'},
 'BuddyPress': {'html': ['/wp-content/plugins/buddypress/', 'buddypress'], 'category': 'WordPress Plugin'},
 'bbPress': {'html': ['/wp-content/plugins/bbpress/', 'bbpress'], 'category': 'WordPress Plugin'},
 'The Events Calendar': {'html': ['/wp-content/plugins/the-events-calendar/', 'the-events-calendar'],
                         'category': 'WordPress Plugin'},
 'Advanced Custom Fields': {'html': ['/wp-content/plugins/advanced-custom-fields/', 'acf'],
                            'category': 'WordPress Plugin'},
 'ACF Pro': {'html': ['/wp-content/plugins/advanced-custom-fields-pro/', 'acf-pro'], 'category': 'WordPress Plugin'},
 'Jetpack': {'html': ['/wp-content/plugins/jetpack/', 'jetpack'], 'category': 'WordPress Plugin'},
 'Astra': {'html': ['/wp-content/themes/astra/', 'astra'], 'category': 'WordPress Theme'},
 'OceanWP': {'html': ['/wp-content/themes/oceanwp/', 'oceanwp'], 'category': 'WordPress Theme'},
 'Kadence': {'html': ['/wp-content/themes/kadence/', 'kadence'], 'category': 'WordPress Theme'},
 'WP Fastest Cache': {'html': ['/wp-content/plugins/wp-fastest-cache/', 'wpfastestcache'],
                      'category': 'WordPress Plugin'},
 'Perfmatters': {'html': ['/wp-content/plugins/perfmatters/', 'perfmatters'], 'category': 'WordPress Plugin'},
 'WP Reset': {'html': ['/wp-content/plugins/wp-reset/', 'wp-reset'], 'category': 'WordPress Plugin'},
 'WP Cerber': {'html': ['/wp-content/plugins/wp-cerber/', 'wp-cerber'], 'category': 'WordPress Plugin'},
 'Sucuri Security': {'html': ['/wp-content/plugins/sucuri-scanner/', 'sucuri'], 'category': 'WordPress Plugin'},
 'Wordfence': {'html': ['/wp-content/plugins/wordfence/', 'wordfence'], 'category': 'WordPress Plugin'},
 'Solid Security': {'html': ['/wp-content/plugins/solid-security/', 'solidsecurity'], 'category': 'WordPress Plugin'},
 'WP Content Copy Protection': {'html': ['/wp-content/plugins/wp-content-copy-protection/',
                                         'wp-content-copy-protection'],
                                'category': 'WordPress Plugin'},
 'WP Optimize': {'html': ['/wp-content/plugins/wp-optimize/', 'wp-optimize'], 'category': 'WordPress Plugin'},
 'Broken Link Checker': {'html': ['/wp-content/plugins/broken-link-checker/', 'broken-link-checker'],
                         'category': 'WordPress Plugin'},
 'WPForms Lite': {'html': ['/wp-content/plugins/wpforms-lite/', 'wpforms'], 'category': 'WordPress Plugin'},
 'FluentForms': {'html': ['/wp-content/plugins/fluentform/', 'fluentform'], 'category': 'WordPress Plugin'},
 'Forminator': {'html': ['/wp-content/plugins/forminator/', 'forminator'], 'category': 'WordPress Plugin'},
 'Ninja Forms': {'html': ['/wp-content/plugins/ninja-forms/', 'ninja-forms'], 'category': 'WordPress Plugin'},
 'MailPoet': {'html': ['/wp-content/plugins/mailpoet/', 'mailpoet'], 'category': 'WordPress Plugin'},
 'MemberPress': {'html': ['/wp-content/plugins/memberpress/', 'memberpress'], 'category': 'WordPress Plugin'},
 'LearnDash': {'html': ['/wp-content/plugins/learndash/', 'learndash'], 'category': 'WordPress Plugin'},
 'Tutor LMS': {'html': ['/wp-content/plugins/tutor-lms/', 'tutor-lms'], 'category': 'WordPress Plugin'},
 'Restrict Content Pro': {'html': ['/wp-content/plugins/restrict-content-pro/', 'restrict-content-pro'],
                          'category': 'WordPress Plugin'},
 'WooCommerce Subscriptions': {'html': ['/wp-content/plugins/woocommerce-subscriptions/', 'woocommerce-subscriptions'],
                               'category': 'WordPress Plugin'},
 'WooCommerce Memberships': {'html': ['/wp-content/plugins/woocommerce-memberships/', 'woocommerce-memberships'],
                             'category': 'WordPress Plugin'},
 'YITH WooCommerce Wishlist': {'html': ['/wp-content/plugins/yith-woocommerce-wishlist/', 'yith-woocommerce-wishlist'],
                               'category': 'WordPress Plugin'},
 'WooCommerce Bookings': {'html': ['/wp-content/plugins/woocommerce-bookings/', 'woocommerce-bookings'],
                          'category': 'WordPress Plugin'},
 'Slider Revolution': {'html': ['/wp-content/plugins/revslider/', 'revslider'], 'category': 'WordPress Plugin'},
 'LayerSlider': {'html': ['/wp-content/plugins/layerslider/', 'layerslider'], 'category': 'WordPress Plugin'},
 'Envira Gallery': {'html': ['/wp-content/plugins/envira-gallery-lite/', 'envira-gallery'],
                    'category': 'WordPress Plugin'},
 'NextGEN Gallery': {'html': ['/wp-content/plugins/nextgen-gallery/', 'nextgen-gallery'],
                     'category': 'WordPress Plugin'},
 'MetaSlider': {'html': ['/wp-content/plugins/ml-slider/', 'meta-slider'], 'category': 'WordPress Plugin'},
 'WP Job Manager': {'html': ['/wp-content/plugins/wp-job-manager/', 'wp-job-manager'], 'category': 'WordPress Plugin'},
 'GeoDirectory': {'html': ['/wp-content/plugins/geodirectory/', 'geodirectory'], 'category': 'WordPress Plugin'},
 'Drupal': {'headers': {'X-Generator': 'Drupal(?:\\s(\\d+))?'},
            'html': ['/sites/default/files/', 'Drupal\\.settings'],
            'meta': {'generator': 'Drupal(?:\\s(\\d+[\\d.]+))?'},
            'category': 'CMS'},
 'Joomla': {'html': ['/media/jui/', '/components/com_'],
            'meta': {'generator': 'Joomla!(?:\\s(\\d+[\\d.]+))?'},
            'category': 'CMS'},
 'Magento': {'cookies': ['frontend'],
             'html': ['Mage\\.', '/skin/frontend/', 'var BLANK_URL'],
             'category': 'E-Commerce'},
 'Shopify': {'html': ['cdn\\.shopify\\.com', 'Shopify\\.theme', 'shopify'],
             'category': 'E-Commerce',
             'scripts': ['cdn\\.shopify\\.com']},
 'BigCommerce': {'html': ['bigcommerce', 'cdn\\.bigcommerce'], 'category': 'CMS / E-Commerce'},
 'PrestaShop': {'html': ['prestashop', 'PrestaShop'], 'category': 'CMS / E-Commerce'},
 'OpenCart': {'html': ['opencart', 'OpenCart'], 'category': 'CMS / E-Commerce'},
 'osCommerce': {'html': ['oscommerce', 'osCommerce'], 'category': 'CMS / E-Commerce'},
 'Zen Cart': {'html': ['zencart', 'Zen Cart'], 'category': 'CMS / E-Commerce'},
 'X-Cart': {'html': ['x-cart', 'X-Cart'], 'category': 'CMS / E-Commerce'},
 'Miva Merchant': {'html': ['miva', 'Miva'], 'category': 'CMS / E-Commerce'},
 'CS-Cart': {'html': ['cs-cart', 'CS-Cart'], 'category': 'CMS / E-Commerce'},
 'Ghost': {'meta': {'generator': 'Ghost(?:\\s(\\d+[\\d.]+))?'},
           'html': ['ghost\\.org', 'content="Ghost'],
           'category': 'CMS'},
 'Concrete CMS': {'html': ['concrete5', 'concrete-cms', '/concrete/'], 'category': 'CMS'},
 'Grav': {'html': ['grav', 'gravatar'], 'category': 'CMS'},
 'ProcessWire': {'html': ['processwire', 'ProcessWire'], 'category': 'CMS'},
 'Bolt CMS': {'html': ['bolt.cm', 'bolt'], 'category': 'CMS'},
 'Pimcore': {'html': ['pimcore', 'Pimcore'], 'category': 'CMS'},
 'Sitecore': {'html': ['sitecore', 'Sitecore'], 'category': 'CMS'},
 'Kentico': {'html': ['kentico', 'Kentico'], 'category': 'CMS'},
 'Umbraco': {'html': ['umbraco', 'Umbraco'], 'category': 'CMS'},
 'Typo3': {'html': ['typo3', 'TYPO3'], 'category': 'CMS'},
 'MODX': {'html': ['modx', 'MODX', '/manager/'], 'category': 'CMS'},
 'SilverStripe': {'html': ['silverstripe', 'SilverStripe'], 'category': 'CMS'},
 'Wix': {'html': ['wixsite\\.com', 'static\\.wixstatic\\.com'], 'category': 'Site Builder'},
 'Squarespace': {'html': ['squarespace\\.com', 'static1\\.squarespace\\.com'], 'category': 'Site Builder'},
 'Webflow': {'html': ['webflow\\.com', 'data-wf-'], 'category': 'Site Builder'},
 'React': {'html': ['__reactFiber',
                    '__reactProps',
                    'react\\.development\\.js',
                    'react\\.production\\.min\\.js',
                    '_reactRootContainer'],
           'scripts': ['react(?:\\.min)?\\.js', 'react-dom'],
           'category': 'JS Framework'},
 'Vue.js': {'html': ['__vue__', 'data-v-', 'vue\\.min\\.js', 'vue\\.js'],
            'scripts': ['vue(?:\\.min)?\\.js'],
            'category': 'JS Framework'},
 'Angular': {'html': ['ng-version=', 'ng-app', 'angular\\.min\\.js'],
             'scripts': ['angular(?:\\.min)?\\.js'],
             'category': 'JS Framework'},
 'Next.js': {'html': ['__NEXT_DATA__', '/_next/static/'],
             'headers': {'X-Powered-By': 'Next\\.js'},
             'category': 'JS Framework'},
 'jQuery': {'html': ['jquery(?:\\.min)?\\.js', 'jQuery v(\\d+[\\d.]+)'],
            'scripts': ['jquery(?:-(\\d+[\\d.]+))?(?:\\.min)?\\.js'],
            'category': 'JS Library'},
 'Lodash': {'html': ['lodash', 'lodash\\.min\\.js'], 'category': 'JS Library'},
 'Underscore.js': {'html': ['underscore', 'underscore\\.min\\.js'], 'category': 'JS Library'},
 'Moment.js': {'html': ['moment', 'moment\\.min\\.js'], 'category': 'JS Library'},
 'D3.js': {'html': ['d3\\.js', 'd3\\.min\\.js'], 'category': 'JS Library'},
 'Three.js': {'html': ['three\\.js', 'three\\.min\\.js'], 'category': 'JS Library'},
 'Chart.js': {'html': ['chart\\.js', 'chart\\.min\\.js'], 'category': 'JS Library'},
 'Highcharts': {'html': ['highcharts', 'highcharts\\.js'], 'category': 'JS Library'},
 'Select2': {'html': ['select2', 'select2\\.js'], 'category': 'JS Library'},
 'Axios': {'html': ['axios', 'axios\\.min\\.js'], 'category': 'JS Library'},
 'Bootstrap': {'html': ['bootstrap(?:\\.min)?\\.css', 'bootstrap(?:\\.min)?\\.js'],
               'scripts': ['bootstrap(?:-(\\d+[\\d.]+))?'],
               'category': 'CSS Framework'},
 'Tailwind CSS': {'html': ['tailwindcss', 'class="[^"]*(?:flex|grid|text-\\w+|bg-\\w+|p-\\d|m-\\d)[^"]*"'],
                  'category': 'CSS Framework'},
 'Bulma': {'html': ['bulma', 'bulma\\.css'], 'category': 'CSS Framework'},
 'Foundation': {'html': ['foundation', 'foundation\\.min\\.css'], 'category': 'CSS Framework'},
 'Materialize': {'html': ['materialize', 'materialize\\.css'], 'category': 'CSS Framework'},
 'UIKit': {'html': ['uikit', 'uikit\\.css'], 'category': 'CSS Framework'},
 'Semantic UI': {'html': ['semantic-ui', 'semantic\\.min\\.css'], 'category': 'CSS Framework'},
 'MUI': {'html': ['@mui', 'mui\\.js'], 'category': 'UI Library'},
 'Gatsby': {'html': ['gatsby', 'gatsby-image'], 'category': 'JS Framework'},
 'Remix': {'html': ['remix', '@remix-run'], 'category': 'JS Framework'},
 'Astro': {'html': ['astro', '@astrojs'], 'category': 'JS Framework'},
 'Vite': {'html': ['vite', '@vitejs'], 'category': 'Build Tool'},
 'Webpack': {'html': ['webpack', 'webpack.js'], 'category': 'Build Tool'},
 'Parcel': {'html': ['parcel', 'parcel-bundler'], 'category': 'Build Tool'},
 'Rollup': {'html': ['rollup', 'rollupjs'], 'category': 'Build Tool'},
 'Cloudflare': {'headers': {'CF-Ray': '.+', 'Server': 'cloudflare'}, 'category': 'CDN / Security'},
 'Cloudflare Turnstile': {'html': ['turnstile', 'cf-turnstile'], 'category': 'Security'},
 'Fastly': {'headers': {'Fastly-Debug-Digest': '.+', 'X-Served-By': 'cache-'}, 'category': 'CDN'},
 'Akamai': {'headers': {'X-Akamai-Transformed': '.+', 'X-Check-Cacheable': '.+'}, 'category': 'CDN'},
 'BunnyCDN': {'html': ['bunnycdn', 'b-cdn.net'], 'category': 'CDN'},
 'jsDelivr': {'html': ['jsdelivr', 'cdn.jsdelivr.net'], 'category': 'CDN'},
 'unpkg': {'html': ['unpkg', 'unpkg.com'], 'category': 'CDN'},
 'cdnjs': {'html': ['cdnjs', 'cdnjs.cloudflare.com'], 'category': 'CDN'},
 'AWS': {'headers': {'x-amz-request-id': '.+', 'x-amz-id-2': '.+'},
         'html': ['amazonaws\\.com', 'awsstatic'],
         'category': 'Cloud'},
 'Google Cloud': {'html': ['cloud\\.google\\.com', 'storage\\.googleapis\\.com'], 'category': 'Cloud'},
 'Heroku': {'html': ['herokuapp\\.com', 'heroku'], 'category': 'Hosting', 'headers': {'Via': '1\\.1 vegur'}},
 'DigitalOcean': {'html': ['digitalocean', 'digitaloceanspaces\\.com'], 'category': 'Cloud'},
 'Vercel': {'html': ['vercel\\.app', '_next', 'vercel'],
            'category': 'Hosting',
            'headers': {'X-Vercel-Id': '.+', 'Server': 'Vercel'}},
 'Cloudflare Pages': {'headers': {'Server': 'cloudflare'},
                      'html': ['cloudflarepages', 'pages.dev'],
                      'category': 'Hosting'},
 'Sentry': {'html': ['sentry', 'sentry.io'], 'scripts': ['sentry'], 'category': 'Monitoring'},
 'Rollbar': {'html': ['rollbar', 'rollbar.com'], 'category': 'Error Tracking'},
 'Bugsnag': {'html': ['bugsnag', 'bugsnag.com'], 'category': 'Error Tracking'},
 'LogRocket': {'html': ['logrocket', 'logrocket.com'], 'category': 'Error Tracking'},
 'New Relic': {'html': ['newrelic', 'newrelic.com', 'New Relic'], 'category': 'Monitoring'},
 'Datadog': {'html': ['datadoghq', 'datadog', 'Datadog'], 'category': 'Monitoring'},
 'AWS CloudFront': {'headers': {'X-Amz-Cf-Id': '.+', 'Via': 'CloudFront'}, 'category': 'CDN'},
 'Varnish': {'headers': {'X-Varnish': '.+', 'Via': 'varnish'}, 'category': 'Cache'},
 'AWS WAF': {'headers': {'X-AMZ-WAF': '.+'}, 'category': 'WAF'},
 'Sucuri': {'headers': {'X-Sucuri-ID': '.+', 'Server': 'Sucuri'}, 'category': 'WAF'},
 'Imperva': {'headers': {'X-Iinfo': '.+'}, 'category': 'WAF'},
 'ModSecurity': {'headers': {'X-Mod-Security': '.+'}, 'category': 'WAF'},
 'Google Analytics': {'html': ['google-analytics\\.com/analytics\\.js', 'gtag\\(', 'UA-\\d+-\\d+', 'G-[A-Z0-9]+'],
                      'scripts': ['google-analytics\\.com', 'googletagmanager\\.com'],
                      'category': 'Analytics'},
 'Google Tag Manager': {'html': ['googletagmanager\\.com/gtm\\.js', 'GTM-[A-Z0-9]+'],
                        'scripts': ['googletagmanager\\.com'],
                        'category': 'Analytics'},
 'Meta Pixel': {'html': ['fbq\\(', 'facebook\\.com/tr'],
                'scripts': ['connect\\.facebook\\.net'],
                'category': 'Marketing'},
 'TikTok Pixel': {'html': ['ttq\\.track', 'tiktok\\.com'],
                  'scripts': ['analytics\\.tiktok\\.com'],
                  'category': 'Marketing'},
 'HubSpot': {'html': ['hs-scripts\\.com', 'hubspot', 'hubspotusercontent', 'hs-analytics'],
             'scripts': ['hs-scripts\\.com', 'hubspot'],
             'category': 'Marketing'},
 'Mailchimp': {'html': ['mailchimp', 'mc-embed'], 'category': 'Marketing'},
 'Pardot': {'html': ['pardot', 'piwik\\.tracking'], 'category': 'Marketing'},
 'Customer.io': {'html': ['customer\\.io', 'customerio'], 'category': 'Marketing'},
 'Hotjar': {'html': ['hotjar\\.com', 'hjid:', 'hjsv:', 'hotjar'], 'scripts': ['hotjar\\.com'], 'category': 'Analytics'},
 'Mixpanel': {'html': ['mixpanel', 'mixpanel\\.com', 'mixpanel.com'], 'category': 'Analytics'},
 'Segment': {'html': ['segment\\.com', 'analytics\\.js'], 'category': 'Analytics'},
 'Adobe Analytics': {'html': ['s_code\\.js', 'satelliteLib', 'AppMeasurement'], 'category': 'Analytics'},
 'Amplitude': {'html': ['amplitude', 'amplitude\\.com'], 'category': 'Analytics'},
 'Heap': {'html': ['heap\\.io', 'heap-'], 'category': 'Analytics'},
 'Crazy Egg': {'html': ['crazyegg', 'ce\\.js'], 'category': 'Analytics'},
 'Matomo': {'html': ['matomo\\.js', 'piwik\\.js', '_paq\\.push'], 'category': 'Analytics'},
 'Plausible': {'html': ['plausible\\.io/js'], 'category': 'Analytics'},
 'HSTS': {'headers': {'Strict-Transport-Security': '.+'}, 'category': 'Security Header'},
 'CSP': {'headers': {'Content-Security-Policy': '.+'}, 'category': 'Security Header'},
 'X-Frame-Options': {'headers': {'X-Frame-Options': '.+'}, 'category': 'Security Header'},
 'X-XSS-Protection': {'headers': {'X-XSS-Protection': '.+'}, 'category': 'Security Header'},
 'MySQL': {'html': ['mysql_connect', 'MySQL'], 'category': 'Database'},
 'MongoDB': {'html': ['mongodb', 'MongoClient'], 'category': 'Database'},
 'Elasticsearch': {'html': ['elasticsearch', 'elastic\\.co'], 'category': 'Search Engine'},
 'Netlify': {'headers': {'X-Nf-Request-Id': '.+', 'Server': 'Netlify'}, 'category': 'Hosting'},
 'GitHub Pages': {'html': ['github\\.io'], 'category': 'Hosting'},
 'Stripe': {'html': ['js\\.stripe\\.com', 'Stripe\\('], 'scripts': ['js\\.stripe\\.com'], 'category': 'Payment'},
 'PayPal': {'html': ['paypal\\.com/sdk', 'paypalobjects\\.com'], 'category': 'Payment'},
 'Klarna': {'html': ['klarna', 'klarna\\.com'], 'category': 'Payment'},
 'Apple Pay': {'html': ['apple-pay', 'paymentrequest'], 'category': 'Payment'},
 'ReCharge': {'html': ['recharge', 'rechargeapps\\.com'], 'category': 'E-Commerce'},
 'Bold Commerce': {'html': ['bold\\.commerce', 'boldapps'], 'category': 'E-Commerce'},
 'Skio': {'html': ['skio', 'skiopages'], 'category': 'E-Commerce'},
 'ShipStation': {'html': ['shipstation', 'shipstation\\.com'], 'category': 'Fulfillment'},
 'ShipBob': {'html': ['shipbob', 'shipbob\\.com'], 'category': 'Fulfillment'},
 'Easyship': {'html': ['easyship', 'easyship\\.com'], 'category': 'Fulfillment'},
 'Zendesk': {'html': ['zendesk', 'zendesk\\.com', 'zE\\('], 'category': 'CRM / Chat'},
 'Intercom': {'html': ['intercom', 'intercom\\.io', 'intercomSettings'], 'category': 'CRM / Chat'},
 'Salesforce': {'html': ['salesforce', 'force\\.com'], 'category': 'CRM'},
 'Pipedrive': {'html': ['pipedrive', 'pipedrive\\.com'], 'category': 'CRM'},
 'Drift': {'html': ['drift', 'drift\\.com'], 'category': 'CRM'},
 'Calendly': {'html': ['calendly', 'calendly\\.com'], 'category': 'Scheduling'},
 'Typeform': {'html': ['typeform', 'typeform\\.com'], 'category': 'Forms'},
 'Jotform': {'html': ['jotform', 'jotform\\.com'], 'category': 'Forms'},
 'Braintree': {'html': ['braintreegateway\\.com', 'paypal\\.com/sdk'], 'category': 'Payment'},
 'Authorize.Net': {'html': ['authorize\\.net', 'accept\\.js'], 'category': 'Payment'},
 'Square': {'html': ['squareup\\.com', 'sqpaymentform'], 'category': 'Payment'},
 'Adyen': {'html': ['adyen\\.com', 'adyen'], 'category': 'Payment'},
 'Checkout.com': {'html': ['checkout\\.com', 'cko'], 'category': 'Payment'},
 'Paddle': {'html': ['paddle\\.com', 'paddle'], 'category': 'Payment'},
 'Font Awesome': {'html': ['font-awesome', 'fontawesome'], 'scripts': ['fontawesome'], 'category': 'UI Library'},
 'reCAPTCHA': {'html': ['google\\.com/recaptcha', 'grecaptcha'], 'category': 'Security'},
 'Tomcat': {'headers': {'Server': 'Tomcat(?:/(\\d+[\\d.]+))?', 'X-Powered-By': 'Tomcat'},
            'cookies': ['JSESSIONID'],
            'html': ['/manager/html', 'tomcat', '/docs/config'],
            'paths': ['/manager/html', '/host-manager/html', '/docs'],
            'category': 'Web Server'},
 'Jenkins': {'headers': {'X-Jenkins': '.+', 'Server': 'Jenkins'},
             'html': ['Jenkins', 'jenkins-ci\\.org', '/static/jenkins', 'jenkins'],
             'paths': ['/login', '/script', '/manage', '/jenkins'],
             'category': 'CI/CD'},
 'Nifi': {'headers': {'Server': 'NiFi'},
          'html': ['NiFi', '/nifi/', 'nifi-api'],
          'paths': ['/nifi', '/nifi/login', '/nifi-api'],
          'category': 'Data Platform'},
 'Grafana': {'headers': {'Server': 'Grafana'},
             'html': ['Grafana', 'grafana-static', '/login', 'grafana'],
             'category': 'Monitoring',
             'paths': ['/grafana', '/login']},
 'Kibana': {'html': ['Kibana', 'app/kibana', 'kibana'], 'category': 'Analytics', 'paths': ['/app/kibana']},
 'Prometheus': {'html': ['Prometheus', '/graph', '/api/v1/targets', 'prometheus'],
                'category': 'Monitoring',
                'paths': ['/graph']},
 'OpenSSH': {'headers': {'Server': 'OpenSSH(?:/(\\d+[\\d.]+))?'}, 'category': 'Remote Access'},
 'RabbitMQ': {'headers': {'Server': 'RabbitMQ'}, 'html': ['RabbitMQ', '/api/health'], 'category': 'Messaging'},
 'Redis': {'headers': {'Server': 'Redis'}, 'html': ['redis_version', 'Redis', '/info'], 'category': 'Database'},
 'PostgreSQL': {'html': ['PostgreSQL', 'pgAdmin', '/pgadmin'], 'category': 'Database'},
 'pgAdmin': {'html': ['pgAdmin', 'pgadmin'], 'category': 'Database Admin', 'paths': ['/pgadmin4', '/pgadmin']},
 'Apache Solr': {'html': ['Apache Solr', '/solr/', 'solr'], 'category': 'Search Engine'},
 'OpenSearch': {'html': ['OpenSearch', 'opensearch'], 'category': 'Search Engine'},
 'Zookeeper': {'html': ['Zookeeper', 'zk', 'zookeeper'], 'category': 'Distributed Systems'},
 'Kafka': {'html': ['Kafka', 'kafka-ui', 'kafkaconsumer'], 'category': 'Messaging'},
 'ActiveMQ': {'html': ['ActiveMQ', 'activemq'], 'category': 'Messaging'},
 'Consul': {'html': ['Consul', 'consul'], 'category': 'Service Discovery'},
 'Vault': {'html': ['Vault', 'vault'], 'category': 'Secrets Management'},
 'Harbor': {'html': ['Harbor', 'harbor-registry', 'harbor'],
            'category': 'Container Registry',
            'paths': ['/harbor', '/harbor/sign-in']},
 'GitLab': {'html': ['GitLab', 'gitlab-ce', 'gitlab'],
            'paths': ['/users/sign_in', '/explore', '/profile', '/gitlab'],
            'category': 'DevOps'},
 'Gitea': {'html': ['Gitea', 'gitea'], 'category': 'DevOps', 'paths': ['/user/login', '/gitea']},
 'Jira': {'html': ['Jira', 'atlassian\\.net', 'jira'], 'category': 'Project Mgmt', 'paths': ['/login.jsp', '/jira']},
 'Confluence': {'html': ['Confluence', 'confluence', 'atlassian'],
                'category': 'Collaboration',
                'paths': ['/login.action', '/confluence']},
 'SonarQube': {'html': ['SonarQube', 'sonarqube', 'sonar'], 'category': 'Code Quality'},
 'TeamCity': {'html': ['TeamCity', 'teamcity'], 'category': 'CI/CD', 'paths': ['/login.html', '/teamcity']},
 'Bitbucket': {'html': ['Bitbucket', 'bitbucket'], 'category': 'DevOps', 'paths': ['/login', '/bitbucket']},
 'Rancher': {'html': ['Rancher', 'rancher'], 'category': 'Container Mgmt', 'paths': ['/dashboard', '/login']},
 'Portainer': {'html': ['Portainer', 'portainer'], 'category': 'Container Mgmt', 'paths': ['/portainer', '/#!/auth']},
 'Mattermost': {'html': ['Mattermost', 'mattermost'],
                'category': 'Collaboration',
                'paths': ['/signup_user_complete', '/mattermost']},
 'OpenVPN': {'headers': {'Server': 'OpenVPN'},
             'html': ['OpenVPN', 'openvpn'],
             'paths': ['/admin', '/openvpn', '/login'],
             'category': 'VPN / Remote Access'},
 'pfSense': {'html': ['pfSense', 'pfsense'],
             'category': 'Firewall / Network',
             'paths': ['/diag', '/system_usermanager.php']},
 'Nagios': {'html': ['Nagios', 'nagios'], 'category': 'Monitoring', 'paths': ['/nagios', '/cgi-bin/status.cgi']},
 'Zabbix': {'html': ['Zabbix', 'zabbix'], 'category': 'Monitoring', 'paths': ['/zabbix', '/index.php']},
 'Cacti': {'html': ['Cacti', 'cacti'], 'category': 'Monitoring', 'paths': ['/cacti']},
 'Splunk': {'html': ['Splunk', 'splunkd'], 'category': 'Monitoring'},
 'Graylog': {'html': ['Graylog', 'graylog'], 'category': 'Monitoring'},
 'Keycloak': {'html': ['Keycloak', 'keycloak'], 'category': 'Identity'},
 'Apache Guacamole': {'html': ['Guacamole', 'guacamole'],
                      'paths': ['/guacamole', '/guacamole/login'],
                      'category': 'Remote Access'},
 'NetBox': {'html': ['NetBox', 'netbox'], 'category': 'Infrastructure', 'paths': ['/netbox', '/login']},
 'LibreNMS': {'html': ['LibreNMS', 'librenms'], 'category': 'Monitoring', 'paths': ['/librenms', '/login']},
 'Apache Superset': {'html': ['Superset', 'superset', 'Apache Superset'], 'category': 'Analytics'},
 'Metabase': {'html': ['Metabase', 'metabase'], 'category': 'Analytics'},
 'Airflow': {'html': ['Airflow', 'airflow'], 'category': 'Data Platform'},
 'Plesk': {'html': ['Plesk', 'plesk'], 'paths': ['/smb/web/plesk', '/login_up.php'], 'category': 'Hosting Panel'},
 'cPanel': {'html': ['cPanel', 'cpanel'], 'paths': ['/cpanel', '/whm'], 'category': 'Hosting'},
 'DirectAdmin': {'html': ['DirectAdmin', 'directadmin'],
                 'paths': ['/CMD_LOGIN', '/CMD_HTTPD_CONF'],
                 'category': 'Hosting Panel'},
 'Webmin': {'html': ['Webmin', 'webmin'], 'paths': ['/webmin', '/session_login.cgi'], 'category': 'Admin Panel'},
 'phpMyAdmin': {'html': ['phpMyAdmin', 'phpmyadmin'],
                'paths': ['/phpmyadmin', '/phpMyAdmin', '/pma', '/sql'],
                'category': 'Database Admin'},
 'Adminer': {'html': ['Adminer', 'adminer'], 'paths': ['/adminer', '/adminer.php'], 'category': 'Database Admin'},
 'RedisInsight': {'html': ['RedisInsight', 'redisinsight', 'redis'],
                  'paths': ['/redisinsight', '/redis'],
                  'category': 'Database'},
 'Mongo Express': {'html': ['Mongo Express', 'mongo-express', 'mongo'],
                   'paths': ['/mongo-express', '/mongo'],
                   'category': 'Database'},
 'RabbitMQ Management': {'html': ['RabbitMQ Management', 'rabbitmq'],
                         'paths': ['/rabbitmq', '/rabbitmq/#/login'],
                         'category': 'Messaging'},
 'Kafka Manager': {'html': ['Kafka Manager', 'kafka-manager', 'kafka'],
                   'paths': ['/kafka-manager', '/manager/html'],
                   'category': 'Messaging'},
 'ActiveMQ Console': {'html': ['ActiveMQ Console', 'activemq'],
                      'paths': ['/admin', '/console'],
                      'category': 'Messaging'},
 'Nifi UI': {'html': ['Nifi UI', 'nifi'], 'paths': ['/nifi', '/nifi/login'], 'category': 'Data Platform'},
 'Jupyter Notebook': {'html': ['Jupyter Notebook', 'jupyter'], 'paths': ['/tree', '/lab'], 'category': 'Data Platform'},
 'RStudio Server': {'html': ['RStudio Server', 'rstudio'],
                    'paths': ['/rstudio', '/auth-sign-in'],
                    'category': 'Data Platform'},
 'OpenWebUI': {'html': ['OpenWebUI', 'openwebui'], 'paths': ['/openwebui', '/auth/login'], 'category': 'AI / ML'},
 'Uptime Kuma': {'html': ['Uptime Kuma', 'uptime-kuma'], 'paths': ['/status', '/dashboard'], 'category': 'Monitoring'},
 'Kasm Workspaces': {'html': ['Kasm Workspaces', 'kasm'], 'paths': ['/login', '/#/login'], 'category': 'Admin Panel'},
 'Redmine': {'html': ['Redmine', 'redmine'], 'paths': ['/login', '/redmine'], 'category': 'Project Mgmt'},
 'Rocket.Chat': {'html': ['Rocket.Chat', 'rocketchat', 'Rocket\\.Chat'],
                 'paths': ['/home', '/rocketchat'],
                 'category': 'Collaboration'},
 'Nextcloud': {'html': ['Nextcloud', 'nextcloud'], 'paths': ['/nextcloud', '/login'], 'category': 'File Sharing'},
 'OwnCloud': {'html': ['OwnCloud', 'owncloud'], 'paths': ['/owncloud', '/login'], 'category': 'File Sharing'},
 'Pydio': {'html': ['Pydio', 'pydio'], 'paths': ['/pydio', '/login'], 'category': 'File Sharing'},
 'OpenMediaVault': {'html': ['OpenMediaVault', 'omv', 'openmediavault'],
                    'paths': ['/omv', '/login'],
                    'category': 'NAS'},
 'FreeNAS': {'html': ['FreeNAS', 'freenas'], 'paths': ['/ui', '/login'], 'category': 'NAS'},
 'Mikrotik RouterOS': {'html': ['MikroTik', 'routeros'], 'paths': ['/webfig', '/login'], 'category': 'Admin Panel'},
 'OPNsense': {'html': ['OPNsense', 'opnsense'], 'paths': ['/diag', '/ui/'], 'category': 'Firewall / Network'},
 'Sophos UTM': {'html': ['Sophos UTM', 'sophos'], 'paths': ['/userportal', '/login'], 'category': 'Security'},
 'FortiGate': {'html': ['FortiGate', 'fortigate'], 'paths': ['/login', '/ng'], 'category': 'Firewall'},
 'Cisco Meraki': {'html': ['Meraki', 'cisco'], 'paths': ['/login', '/nms'], 'category': 'Network Admin'},
 'Ubiquiti UniFi': {'html': ['UniFi', 'unifi'], 'paths': ['/manage', '/login'], 'category': 'Admin Panel'},
 'Roundcube': {'html': ['Roundcube', 'roundcube'], 'category': 'Mail'},
 'Mailcow': {'html': ['Mailcow', 'mailcow'], 'category': 'Mail'},
 'Mautic': {'html': ['Mautic', 'mautic'], 'category': 'Marketing', 'paths': ['/s/mautic', '/index.php/mautic']},
 'Discourse': {'html': ['Discourse', 'discourse'], 'category': 'Forum'},
 'Flarum': {'html': ['Flarum', 'flarum'], 'category': 'Forum'},
 'Drupal 7': {'html': ['drupal\\.org', '/sites/all/themes/', '/misc/drupal.js'], 'category': 'CMS'},
 'TYPO3': {'html': ['TYPO3', '/typo3/'], 'category': 'CMS'},
 'Moodle': {'html': ['Moodle', '/theme/image.php'], 'category': 'Learning Platform'},
 'Sendinblue': {'html': ['sendinblue', 'sib-cp'], 'category': 'Marketing'},
 'SEOmatic': {'html': ['SEOmatic', 'seomatic'], 'category': 'SEO'},
 'Matomo Analytics': {'html': ['matomo', '_paq\\.push'], 'category': 'Analytics'},
 'Piwik': {'html': ['piwik', '_paq\\.push'], 'category': 'Analytics'},
 'Tawk.to': {'html': ['tawk', 'tawk\\.to'], 'category': 'CRM / Chat'},
 'LiveChat': {'html': ['livechat', 'lc\\.widget'], 'category': 'CRM / Chat'},
 'Formspree': {'html': ['formspree', 'formspree\\.io'], 'category': 'Forms'},
 'Telerik UI': {'html': ['telerik', 'kendo\\.all'], 'category': 'UI Library'},
 'Material UI': {'html': ['mui', '@material-ui'], 'category': 'UI Library'},
 'AEM': {'html': ['/etc.clientlibs/', 'Adobe Experience Manager', 'aem'], 'category': 'CMS'},
 'Liferay': {'html': ['Liferay', 'liferay'], 'category': 'Portal'},
 'Oracle WebLogic': {'html': ['WebLogic', 'weblogic'], 'category': 'Application Server'},
 'IBM WebSphere': {'html': ['WebSphere', 'websphere'], 'category': 'Application Server'},
 'GlassFish': {'html': ['GlassFish', 'glassfish'], 'category': 'Application Server'},
 'WildFly': {'html': ['WildFly', 'wildfly'], 'category': 'Application Server'},
 'Jetty': {'html': ['Jetty', 'jetty'], 'category': 'Web Server'},
 'Boa': {'html': ['Boa', 'boa'], 'category': 'Web Server'},
 'Cherokee': {'html': ['Cherokee', 'cherokee'], 'category': 'Web Server'},
 'traefik': {'headers': {'Server': 'traefik'}, 'category': 'Reverse Proxy'},
 'HAProxy': {'headers': {'Server': 'HAProxy'}, 'category': 'Load Balancer'},
 'Envoy': {'headers': {'Server': 'envoy'}, 'category': 'Proxy'},
 'Cloudflare Tunnel': {'headers': {'Server': 'cloudflared'}, 'category': 'CDN / Security'},
 'Akamai Ghost': {'headers': {'Server': 'AkamaiGHost'}, 'category': 'CDN'},
 'F5 BIG-IP': {'html': ['BIG-IP', 'F5'], 'category': 'Load Balancer'},
 'Nexus Repository': {'html': ['Nexus Repository', 'nexus'],
                      'paths': ['/nexus', '/repository'],
                      'category': 'Artifact Repository'},
 'Artifactory': {'html': ['Artifactory', 'artifactory'],
                 'paths': ['/artifactory', '/ui/repos'],
                 'category': 'Artifact Repository'},
 'Sonatype Nexus': {'html': ['Sonatype', 'nexus'], 'category': 'Artifact Repository'},
 'Apache Airflow': {'html': ['Airflow', 'airflow'], 'category': 'Data Platform'},
 'Superset': {'html': ['Superset', 'superset'], 'category': 'Data Platform'},
 'DataDog': {'html': ['datadoghq', 'datadog'], 'category': 'Monitoring'},
 'Elastic Stack': {'html': ['elasticsearch', 'kibana', 'elastic'], 'category': 'Monitoring'},
 'OpenTelemetry': {'html': ['opentelemetry', 'otel'], 'category': 'Monitoring'},
 'Splunk Enterprise': {'html': ['Splunk Enterprise', 'splunkd'], 'category': 'Monitoring'},
 'Apache Druid': {'html': ['Druid', 'druid'], 'category': 'Data Platform'},
 'ClickHouse': {'html': ['ClickHouse', 'clickhouse'], 'category': 'Database'},
 'CouchDB': {'html': ['CouchDB', 'couchdb'], 'category': 'Database'},
 'Neo4j': {'html': ['neo4j', 'Neo4j'], 'category': 'Database'},
 'Memcached': {'html': ['Memcached', 'memcached'], 'category': 'Cache'},
 'Airtable': {'html': ['airtable', 'airtable\\.com'], 'category': 'SaaS'},
 'Notion': {'html': ['notion', 'notion\\.so'], 'category': 'SaaS'},
 'Trello': {'html': ['trello', 'trello\\.com'], 'category': 'SaaS'},
 'Asana': {'html': ['asana', 'asana\\.com'], 'category': 'SaaS'},
 'Slack': {'html': ['slack', 'slack\\.com'], 'category': 'SaaS'},
 'Dropbox': {'html': ['dropbox', 'dropbox\\.com'], 'category': 'SaaS'},
 'Google Workspace': {'html': ['workspace\\.google\\.com', 'googleusercontent'], 'category': 'SaaS'},
 'Microsoft 365': {'html': ['office\\.com', 'sharepoint'], 'category': 'SaaS'},
 'Atlassian': {'html': ['atlassian', 'jira', 'confluence'], 'category': 'SaaS'},
 'GitHub': {'html': ['github\\.com', 'githubusercontent', 'GitHub', 'github'], 'category': 'DevOps'},
 'GitLab CE': {'html': ['gitlab', 'gitlab-ce', 'GitLab CE'], 'category': 'DevOps'},
 'Bitbucket Server': {'html': ['bitbucket', 'bitbucketserver', 'Bitbucket Server'], 'category': 'DevOps'},
 'Jenkins X': {'html': ['jenkins-x', 'jenkinsx', 'Jenkins X'], 'category': 'CI / CD'},
 'CircleCI': {'html': ['circleci', 'circleci\\.com', 'CircleCI'], 'category': 'CI / CD'},
 'Travis CI': {'html': ['travis', 'travis-ci', 'Travis CI'], 'category': 'CI / CD'},
 'GoCD': {'html': ['go-cd', 'gocd', 'GoCD'], 'category': 'CI / CD'},
 'Bamboo': {'html': ['Bamboo', 'bamboo'], 'category': 'CI / CD'},
 'Drone': {'html': ['Drone', 'drone'], 'category': 'CI / CD'},
 'Woodstock': {'html': ['woodstock', 'woodstock'], 'category': 'Framework'},
 'Apache Cocoon': {'html': ['Apache Cocoon', 'cocoon'], 'category': 'Framework'},
 'Deno': {'html': ['Deno', 'deno\\.dev'], 'category': 'Language'},
 'Go': {'html': ['Go', 'golang'], 'category': 'Language'},
 'Rust': {'html': ['Rust', 'cargo'], 'category': 'Language'},
 'Scala': {'html': ['Scala', 'scala'], 'category': 'Language'},
 'Erlang': {'html': ['Erlang', 'erlang'], 'category': 'Language'},
 'Lua': {'html': ['Lua', 'lua'], 'category': 'Language'},
 'Perl': {'html': ['Perl', 'perl'], 'category': 'Language'},
 'Hadoop': {'html': ['Hadoop', 'hadoop'], 'category': 'Data Platform'},
 'Spark': {'html': ['Spark', 'spark'], 'category': 'Data Platform'},
 'TensorFlow': {'html': ['TensorFlow', 'tensorflow'], 'category': 'AI / ML'},
 'PyTorch': {'html': ['PyTorch', 'pytorch'], 'category': 'AI / ML'},
 'Scikit-learn': {'html': ['scikit-learn', 'sklearn'], 'category': 'AI / ML'},
 'Jupyter': {'html': ['Jupyter', 'jupyter'], 'category': 'Data Platform'},
 'RStudio': {'html': ['RStudio', 'rstudio'], 'category': 'Data Platform'},
 'Shiny': {'html': ['Shiny', 'shiny'], 'category': 'Data Platform'},
 'OpenMPI': {'html': ['OpenMPI', 'mpi'], 'category': 'Infrastructure'},
 'Puppet': {'html': ['Puppet', 'puppet'], 'category': 'Config Management'},
 'Ansible': {'html': ['Ansible', 'ansible'], 'category': 'Config Management'},
 'Chef': {'html': ['Chef', 'chef'], 'category': 'Config Management'},
 'SaltStack': {'html': ['SaltStack', 'salt'], 'category': 'Config Management'},
 'Terraform': {'html': ['Terraform', 'terraform'], 'category': 'Infrastructure'},
 'Kubernetes': {'html': ['Kubernetes', 'kubernetes'], 'category': 'Container Orchestration'},
 'Docker': {'html': ['Docker', 'docker'], 'category': 'Container Orchestration'},
 'Podman': {'html': ['Podman', 'podman'], 'category': 'Container Orchestration'},
 'OpenShift': {'html': ['OpenShift', 'openshift'],
               'category': 'Container Orchestration',
               'paths': ['/oauth', '/console']},
 'K3s': {'html': ['K3s', 'k3s'], 'category': 'Container Orchestration'},
 'OpenStack': {'html': ['OpenStack', 'openstack'], 'category': 'Cloud'},
 'OpenStack Horizon': {'html': ['Horizon', 'openstack'], 'paths': ['/horizon', '/auth/login'], 'category': 'Cloud'},
 'OpenStack Keystone': {'html': ['Keystone', 'keystone'],
                        'paths': ['/v3/auth/tokens', '/identity'],
                        'category': 'Cloud'},
 'OpenStack Nova': {'html': ['Nova', 'nova'], 'category': 'Cloud'},
 'OpenStack Cinder': {'html': ['Cinder', 'cinder'], 'category': 'Cloud'},
 'OpenStack Neutron': {'html': ['Neutron', 'neutron'], 'category': 'Cloud'},
 'OpenStack Swift': {'html': ['Swift', 'swift'], 'category': 'Cloud'},
 'OpenStack Glance': {'html': ['Glance', 'glance'], 'category': 'Cloud'},
 'OpenStack Heat': {'html': ['Heat', 'heat'], 'category': 'Cloud'},
 'OpenNebula': {'html': ['OpenNebula', 'opennebula'], 'paths': ['/oneflow', '/sunstone'], 'category': 'Cloud'},
 'Apache CloudStack': {'html': ['CloudStack', 'cloudstack'], 'paths': ['/client', '/login'], 'category': 'Cloud'},
 'Proxmox VE': {'html': ['Proxmox', 'proxmox'], 'paths': ['/pve', '/nodes'], 'category': 'Virtualization'},
 'oVirt': {'html': ['oVirt', 'ovirt'], 'paths': ['/ovirt-engine', '/login'], 'category': 'Virtualization'},
 'OpenShift Console': {'html': ['OpenShift Console', 'openshift'],
                       'paths': ['/console', '/oauth'],
                       'category': 'Container Orchestration'},
 'WireGuard': {'html': ['WireGuard', 'wireguard'], 'paths': ['/wg', '/login'], 'category': 'VPN'},
 'Tailscale': {'html': ['Tailscale', 'tailscale'], 'paths': ['/login', '/admin'], 'category': 'VPN'},
 'Icinga': {'html': ['Icinga', 'icinga'], 'paths': ['/icinga', '/login'], 'category': 'Monitoring'},
 'IPFire': {'html': ['IPFire', 'ipfire'],
            'paths': ['/cgi-bin/console.cgi', '/login'],
            'category': 'Firewall / Network'},
 'Sophos Firewall': {'html': ['Sophos', 'sophos', 'Sophos Firewall'],
                     'paths': ['/userportal', '/login'],
                     'category': 'Firewall / Network'},
 'MikroTik': {'html': ['MikroTik', 'routeros', 'mikrotik'],
              'paths': ['/webfig', '/login'],
              'category': 'Firewall / Network'},
 'UniFi Controller': {'html': ['UniFi', 'unifi'], 'paths': ['/manage', '/login'], 'category': 'Network Admin'},
 'CPanel': {'html': ['cPanel', 'cpanel'], 'paths': ['/cpanel', '/whm'], 'category': 'Hosting Panel'},
 'Virtualmin': {'html': ['Virtualmin', 'virtualmin'], 'paths': ['/virtualmin', '/login'], 'category': 'Hosting Panel'},
 'Webuzo': {'html': ['Webuzo', 'webuzo'], 'paths': ['/webuzo', '/login'], 'category': 'Hosting Panel'},
 'Printer Admin': {'html': ['printer', 'Printer'], 'paths': ['/webman', '/hp/deviceinfo'], 'category': 'Printer / IoT'},
 'HP Printer': {'html': ['HP', 'Printer'], 'paths': ['/hp/deviceinfo', '/index.htm'], 'category': 'Printer / IoT'},
 'Epson Web Config': {'html': ['Epson', 'webconfig'],
                      'paths': ['/PRESENTATION/HTML/TOP/frameset.htm', '/webconfig'],
                      'category': 'Printer / IoT'},
 'Brother Printer': {'html': ['Brother', 'brother'],
                     'paths': ['/general/status.html', '/home/'],
                     'category': 'Printer / IoT'},
 'D-Link Router': {'html': ['D-Link', 'dlink'], 'paths': ['/setup.cgi', '/login'], 'category': 'Router / Firewall'},
 'TP-Link Router': {'html': ['TP-Link', 'tplink'],
                    'paths': ['/userRpm/LoginRpm.htm', '/login'],
                    'category': 'Router / Firewall'},
 'Linksys Router': {'html': ['Linksys', 'linksys'],
                    'paths': ['/Forms/rmLogin.asp', '/login'],
                    'category': 'Router / Firewall'},
 'Asus Router': {'html': ['Asus', 'asus'], 'paths': ['/Main_Login.asp', '/login'], 'category': 'Router / Firewall'},
 'Netgear Router': {'html': ['Netgear', 'netgear'], 'paths': ['/setup.cgi', '/login'], 'category': 'Router / Firewall'},
 'Synology DSM': {'html': ['Synology', 'dsm', 'Synology DSM', 'synology'],
                  'paths': ['/webman', '/login'],
                  'category': 'Storage'},
 'QNAP QTS': {'html': ['QNAP', 'qts', 'QNAP QTS', 'qnap'],
              'paths': ['/cgi-bin/authLogin.cgi', '/login'],
              'category': 'Storage'},
 'TrueNAS': {'html': ['TrueNAS', 'truenas'], 'paths': ['/ui', '/login'], 'category': 'Storage'},
 'Asustor NAS': {'html': ['Asustor', 'asustor'], 'paths': ['/login', '/admin'], 'category': 'NAS'},
 'Western Digital My Cloud': {'html': ['My Cloud', 'mycloud'], 'paths': ['/UI/login', '/login'], 'category': 'NAS'},
 'IP Camera Admin': {'html': ['camera', 'Camera'],
                     'paths': ['/cgi-bin/viewer/video.jpg', '/login'],
                     'category': 'Printer / IoT'},
 'Axis Camera': {'html': ['Axis', 'axis'], 'paths': ['/view/view.shtml', '/login'], 'category': 'Printer / IoT'},
 'Hikvision Camera': {'html': ['Hikvision', 'hikvision'],
                      'paths': ['/doc/page/login.asp', '/login'],
                      'category': 'Printer / IoT'},
 'Dahua Camera': {'html': ['Dahua', 'dahua'], 'paths': ['/cgi-bin/login.cgi', '/login'], 'category': 'Printer / IoT'},
 'Reolink Camera': {'html': ['Reolink', 'reolink'],
                    'paths': ['/cgi-bin/api.cgi', '/login'],
                    'category': 'Printer / IoT'},
 'AVTech Camera': {'html': ['AVTech', 'avtech'],
                   'paths': ['/cgi-bin/viewer/index.cgi', '/login'],
                   'category': 'Printer / IoT'},
 'MikroTik Router': {'html': ['MikroTik', 'routeros'], 'paths': ['/webfig', '/login'], 'category': 'Router / Firewall'},
 'Ubiquiti EdgeRouter': {'html': ['EdgeRouter', 'ubnt'],
                         'paths': ['/login', '/setup'],
                         'category': 'Router / Firewall'},
 'Ubiquiti UniFi Protect': {'html': ['UniFi Protect', 'unifiprotect'],
                            'paths': ['/protect', '/login'],
                            'category': 'Printer / IoT'},
 'Smart Home Hub': {'html': ['hub', 'Home Assistant'], 'paths': ['/lovelace', '/api'], 'category': 'IoT / Automation'},
 'Home Assistant': {'html': ['Home Assistant', 'homeassistant'], 'paths': ['/lovelace', '/api'], 'category': 'IoT'},
 'OpenHAB': {'html': ['OpenHAB', 'openhab'], 'paths': ['/basicui/app', '/login'], 'category': 'IoT'},
 'Domoticz': {'html': ['Domoticz', 'domoticz'], 'paths': ['/login', '/json.htm'], 'category': 'IoT'},
 'Proxmox': {'html': ['Proxmox', 'proxmox'], 'category': 'Virtualization'},
 'VMware': {'html': ['VMware', 'vmware'], 'category': 'Virtualization'},
 'Xen': {'html': ['Xen', 'xen'], 'category': 'Virtualization'},
 'Synology': {'html': ['Synology', 'synology'], 'category': 'Storage'},
 'QNAP': {'html': ['QNAP', 'qnap'], 'category': 'Storage'},
 'Plex': {'html': ['Plex', 'plex'], 'category': 'Media'},
 'Jellyfin': {'html': ['Jellyfin', 'jellyfin'], 'category': 'Media'},
 'Emby': {'html': ['Emby', 'emby'], 'category': 'Media'},
 'Seafile': {'html': ['Seafile', 'seafile'], 'category': 'File Sharing'},
 'OnlyOffice': {'html': ['OnlyOffice', 'onlyoffice'], 'category': 'Collaboration'},
 'MindsDB': {'html': ['MindsDB', 'mindsdb'], 'category': 'AI / ML'},
 'LibreOffice': {'html': ['LibreOffice', 'libreoffice'], 'category': 'Office'},
 'Collabora': {'html': ['Collabora', 'collabora'], 'category': 'Office'},
 'Paperless-ngx': {'html': ['Paperless', 'paperless'], 'category': 'Document Management'},
 'BookStack': {'html': ['BookStack', 'bookstack'], 'category': 'Wiki'},
 'DokuWiki': {'html': ['DokuWiki', 'dokuwiki'], 'category': 'Wiki'},
 'MediaWiki': {'html': ['MediaWiki', 'mediawiki'], 'category': 'Wiki'},
 'XWiki': {'html': ['XWiki', 'xwiki'], 'category': 'Wiki'},
 'MantisBT': {'html': ['MantisBT', 'mantis'], 'category': 'Bug Tracker'},
 'YouTrack': {'html': ['YouTrack', 'youtrack'], 'category': 'Project Management'},
 'Taiga': {'html': ['Taiga', 'taiga'], 'category': 'Project Management'},
 'OpenProject': {'html': ['OpenProject', 'openproject'], 'category': 'Project Management'},
 'Tuleap': {'html': ['Tuleap', 'tuleap'], 'category': 'Project Management'},
 'MISP': {'html': ['MISP', 'misp'], 'category': 'Threat Intelligence'},
 'TheHive': {'html': ['TheHive', 'thehive'], 'category': 'Threat Intelligence'},
 'Cortex': {'html': ['Cortex', 'cortex'], 'category': 'Threat Intelligence'},
 'Shinken': {'html': ['Shinken', 'shinken'], 'category': 'Monitoring'},
 'Pandora FMS': {'html': ['Pandora', 'pandora'], 'category': 'Monitoring'},
 'PRTG': {'html': ['PRTG', 'prtg'], 'category': 'Monitoring'},
 'Mikrotik': {'html': ['MikroTik', 'mikrotik'], 'category': 'Firewall / Network'},
 'Ubiquiti': {'html': ['Ubiquiti', 'ubiquiti'], 'category': 'Firewall / Network'},
 'MikroTik RouterOS': {'html': ['RouterOS', 'mikrotik'], 'category': 'Firewall / Network'},
 'OpenWRT': {'html': ['OpenWrt', 'openwrt'], 'category': 'Firewall / Network'},
 'Palo Alto': {'html': ['Palo Alto', 'paloalto'], 'category': 'Firewall / Network'},
 'Cisco ASA': {'html': ['Cisco ASA', 'cisco'], 'category': 'Networking'},
 'Fortinet': {'html': ['Fortinet', 'fortinet'], 'category': 'Firewall / Network'},
 'Sophos': {'html': ['Sophos', 'sophos'], 'category': 'Firewall / Network'},
 'ClearOS': {'html': ['ClearOS', 'clearos'], 'category': 'Firewall / Network'},
 'Asterisk': {'html': ['Asterisk', 'asterisk'], 'category': 'VoIP'},
 'FreePBX': {'html': ['FreePBX', 'freepbx'], 'category': 'VoIP'},
 'FusionPBX': {'html': ['FusionPBX', 'fusionpbx'], 'category': 'VoIP'},
 '3CX': {'html': ['3CX', '3cx'], 'category': 'VoIP'},
 'Pi-hole': {'html': ['Pi-hole', 'pi-hole'], 'category': 'Network'},
 'Unifi': {'html': ['UniFi', 'unifi'], 'category': 'Network'},
 'ESET': {'html': ['ESET', 'eset'], 'category': 'Security'},
 'Fail2ban': {'html': ['Fail2ban', 'fail2ban'], 'category': 'Security'},
 'Snort': {'html': ['Snort', 'snort'], 'category': 'Security'},
 'Suricata': {'html': ['Suricata', 'suricata'], 'category': 'Security'},
 'ClamAV': {'html': ['ClamAV', 'clamav'], 'category': 'Security'},
 'OpenVAS': {'html': ['OpenVAS', 'openvas'], 'category': 'Security'},
 'OsTicket': {'html': ['osTicket', 'osticket'], 'category': 'Help Desk'},
 'GLPI': {'html': ['GLPI', 'glpi'], 'category': 'Help Desk'},
 'Zammad': {'html': ['Zammad', 'zammad'], 'category': 'Help Desk'},
 'Freshdesk': {'html': ['Freshdesk', 'freshdesk'], 'category': 'Help Desk'},
 'Zoho Desk': {'html': ['Zoho', 'zoho'], 'category': 'Help Desk'},
 'Snipe-IT': {'html': ['Snipe-IT', 'snipeit'], 'category': 'IT Asset Management'},
 'IPAM': {'html': ['IPAM', 'ipam'], 'category': 'Infrastructure'},
 'Rundeck': {'html': ['Rundeck', 'rundeck'],
             'paths': ['/user/login', '/menu/home', '/rundeck'],
             'category': 'Automation'},
 'Ansible Tower': {'html': ['Ansible Tower', 'awx'], 'category': 'Automation'},
 'AWX': {'html': ['AWX', 'awx'], 'category': 'Automation'},
 'Prowler': {'html': ['Prowler', 'prowler'], 'category': 'Security'},
 'Wazuh': {'html': ['Wazuh', 'wazuh'], 'category': 'Security'},
 'Velociraptor': {'html': ['Velociraptor', 'velociraptor'], 'category': 'Security'},
 'Cobalt Strike': {'html': ['Cobalt Strike', 'cobalt'], 'category': 'Security'},
 'Malleable C2': {'html': ['Malleable', 'c2'], 'category': 'Security'},
 'Pulsar': {'html': ['Pulsar', 'pulsar'], 'category': 'Messaging'},
 'NATS': {'html': ['NATS', 'nats'], 'category': 'Messaging'},
 'Mosquitto': {'html': ['Mosquitto', 'mosquitto'], 'category': 'IoT'},
 'Emqx': {'html': ['EMQX', 'emqx'], 'category': 'Messaging'},
 'Apache APISIX': {'html': ['APISIX', 'apisix'], 'category': 'API Gateway'},
 'Kong': {'html': ['Kong', 'kong'], 'category': 'API Gateway'},
 'Tyk': {'html': ['Tyk', 'tyk'], 'category': 'API Gateway'},
 'Gravitee': {'html': ['Gravitee', 'gravitee'], 'category': 'API Gateway'},
 'Wso2': {'html': ['WSO2', 'wso2'], 'category': 'API Gateway'},
 'Nginx Proxy Manager': {'html': ['Nginx Proxy Manager', 'nginxproxymanager'],
                         'paths': ['/admin', '/nginx/proxy'],
                         'category': 'Proxy'},
 'OpenKM': {'html': ['OpenKM', 'openkm'], 'category': 'Document Management'},
 'Alfresco': {'html': ['Alfresco', 'alfresco'], 'category': 'Document Management'},
 'Liferay DXP': {'html': ['Liferay DXP', 'liferay'], 'category': 'Portal'},
 'OpenCms': {'html': ['OpenCms', 'opencms'], 'category': 'CMS'},
 'CMS Made Simple': {'html': ['CMS Made Simple', 'cmsms'], 'category': 'CMS'},
 'Concrete5': {'html': ['Concrete5', 'concrete5'], 'category': 'CMS'},
 'Monstra': {'html': ['Monstra', 'monstra'], 'category': 'CMS'},
 'Pterodactyl': {'html': ['Pterodactyl', 'pterodactyl'],
                 'paths': ['/auth/login', '/admin'],
                 'category': 'Game Server Panel'},
 'Pelican Panel': {'html': ['Pelican', 'pelican'], 'category': 'Game Server Panel'},
 'Multicraft': {'html': ['Multicraft', 'multicraft'], 'category': 'Game Server Panel'},
 'OpenGamePanel': {'html': ['OpenGamePanel', 'opengamepanel'], 'category': 'Game Server Panel'},
 'Pterodactyl Panel': {'html': ['Pterodactyl', 'pterodactyl'], 'category': 'Game Server Panel'},
 'Cockpit': {'html': ['Cockpit', 'cockpit'], 'category': 'Server Admin'},
 'XCP-ng': {'html': ['XCP-ng', 'xcp'], 'category': 'Virtualization'},
 'Hyper-V': {'html': ['Hyper-V', 'hyperv'], 'category': 'Virtualization'},
 'EVE-NG': {'html': ['EVE-NG', 'eve-ng'], 'category': 'Network Lab'},
 'GNS3': {'html': ['GNS3', 'gns3'], 'category': 'Network Lab'},
 'PacketTracer': {'html': ['PacketTracer', 'packettracer'], 'category': 'Network Lab'},
 'OpenWrt': {'html': ['OpenWrt', 'openwrt'], 'category': 'Router'},
 'VyOS': {'html': ['VyOS', 'vyos'], 'category': 'Firewall / Network'},
 'EdgeOS': {'html': ['EdgeOS', 'edgeos'], 'category': 'Firewall / Network'},
 'Zyxel': {'html': ['Zyxel', 'zyxel'], 'category': 'Firewall / Network'},
 'D-Link': {'html': ['D-Link', 'dlink'], 'category': 'Firewall / Network'},
 'Cisco IOS': {'html': ['Cisco IOS', 'cisco'], 'category': 'Networking'},
 'Fortinet FortiGate': {'html': ['FortiGate', 'fortinet'], 'category': 'Firewall / Network'},
 'Aastra': {'html': ['Aastra', 'aastra'], 'category': 'VoIP'},
 'Grandstream': {'html': ['Grandstream', 'grandstream'], 'category': 'VoIP'},
 'Fritz!Box': {'html': ['Fritz!Box', 'fritz'], 'category': 'Router'},
 'MikroTik Winbox': {'html': ['Winbox', 'mikrotik'], 'category': 'Router'},
 'AdGuard Home': {'html': ['AdGuard', 'adguard'], 'category': 'Network'},
 'Raspberry Pi': {'html': ['Raspberry Pi', 'raspberrypi'], 'category': 'Hardware'},
 'OctoPrint': {'html': ['OctoPrint', 'octoprint'], 'category': 'Hardware'},
 'Node-RED': {'html': ['Node-RED', 'nodered'], 'category': 'IoT'},
 'ESPHome': {'html': ['ESPHome', 'esphome'], 'category': 'IoT'},
 'XigmaNAS': {'html': ['XigmaNAS', 'xigmanas'], 'category': 'Storage'},
 'OmniOS': {'html': ['OmniOS', 'omnios'], 'category': 'Storage'},
 'Plex Media Server': {'html': ['Plex Media Server', 'plex'], 'category': 'Media'},
 'Navidrome': {'html': ['Navidrome', 'navidrome'], 'category': 'Media'},
 'Subsonic': {'html': ['Subsonic', 'subsonic'], 'category': 'Media'},
 'Ampache': {'html': ['Ampache', 'ampache'], 'category': 'Media'},
 'FileBrowser': {'html': ['FileBrowser', 'filebrowser'], 'category': 'File Sharing'},
 'SFTPGo': {'html': ['SFTPGo', 'sftpgo'], 'category': 'File Sharing'},
 'Talos': {'html': ['Talos', 'talos'], 'category': 'Container Orchestration'},
 'Nomad': {'html': ['Nomad', 'nomad'], 'category': 'Container Orchestration'},
 'Quay': {'html': ['Quay', 'quay'], 'category': 'Container Registry'},
 'GitBucket': {'html': ['GitBucket', 'gitbucket'], 'category': 'DevOps'},
 'Gogs': {'html': ['Gogs', 'gogs'], 'category': 'DevOps'},
 'Phabricator': {'html': ['Phabricator', 'phabricator'], 'category': 'DevOps'},
 'OpenSUSE': {'html': ['OpenSUSE', 'opensuse'], 'category': 'OS'},
 'Ubuntu': {'headers': {'Server': 'Ubuntu|ubuntu'}, 'category': 'OS'},
 'Debian': {'html': ['Debian', 'debian'], 'category': 'OS'},
 'CentOS': {'html': ['CentOS', 'centos'], 'category': 'OS'},
 'Rocky Linux': {'html': ['Rocky Linux', 'rockylinux'], 'category': 'OS'},
 'AlmaLinux': {'html': ['AlmaLinux', 'almalinux'], 'category': 'OS'},
 'Fedora': {'html': ['Fedora', 'fedora'], 'category': 'OS'},
 'FreeBSD': {'html': ['FreeBSD', 'freebsd'], 'category': 'OS'},
 'OpenBSD': {'html': ['OpenBSD', 'openbsd'], 'category': 'OS'},
 'NetBSD': {'html': ['NetBSD', 'netbsd'], 'category': 'OS'},
 'Windows Server': {'html': ['Windows Server', 'windowsserver'], 'category': 'OS'},
 'Microsoft IIS': {'html': ['Microsoft IIS', 'iis'], 'category': 'Web Server'},
 'Nginx Plus': {'html': ['Nginx Plus', 'nginx'], 'category': 'Web Server'},
 'Apache HTTP Server': {'html': ['Apache HTTP Server', 'apache'], 'category': 'Web Server'},
 'LiteSpeed Web Server': {'html': ['LiteSpeed Web Server', 'litespeed'], 'category': 'Web Server'},
 'Caddy Server': {'html': ['Caddy Server', 'caddy'], 'category': 'Reverse Proxy'},
 'Traefik Proxy': {'html': ['Traefik', 'traefik'], 'category': 'Reverse Proxy'},
 'HAProxy Load Balancer': {'html': ['HAProxy', 'haproxy'], 'category': 'Load Balancer'},
 'Envoy Proxy': {'html': ['Envoy', 'envoy'], 'category': 'Proxy'},
 'OpenVPN Access Server': {'html': ['OpenVPN Access Server', 'openvpn'], 'category': 'VPN'},
 'SoftEther': {'html': ['SoftEther', 'softether'], 'category': 'VPN'},
 'ZeroTier': {'html': ['ZeroTier', 'zerotier'], 'category': 'VPN'},
 'Tor': {'html': ['Tor', 'torproject'], 'category': 'Privacy'},
 'I2P': {'html': ['I2P', 'i2p'], 'category': 'Privacy'},
 'OpenLDAP': {'html': ['OpenLDAP', 'ldap'], 'category': 'Directory'},
 'FreeIPA': {'html': ['FreeIPA', 'freeipa'], 'category': 'Directory'},
 '389 Directory Server': {'html': ['389 Directory Server', '389ds'], 'category': 'Directory'},
 'Samba': {'html': ['Samba', 'samba'], 'category': 'File Sharing'},
 'CUPS': {'html': ['CUPS', 'cups'], 'category': 'Printing'},
 'IPP': {'html': ['IPP', 'ipp'], 'category': 'Printing'},
 'PaperCut': {'html': ['PaperCut', 'papercut'], 'category': 'Printing'},
 'Nagios XI': {'html': ['Nagios XI', 'nagios'], 'category': 'Monitoring'},
 'Zabbix Frontend': {'html': ['Zabbix Frontend', 'zabbix'], 'category': 'Monitoring'},
 'Cacti Monitoring': {'html': ['Cacti Monitoring', 'cacti'], 'category': 'Monitoring'},
 'LibreNMS Monitoring': {'html': ['LibreNMS', 'librenms'], 'category': 'Monitoring'},
 'Prtg Network Monitor': {'html': ['Prtg Network Monitor', 'prtg'], 'category': 'Monitoring'},
 'Auvik': {'html': ['Auvik', 'auvik'], 'category': 'Monitoring'},
 'Grafana Dashboard': {'html': ['Grafana Dashboard', 'grafana'], 'category': 'Monitoring'},
 'Prometheus Metrics': {'html': ['Prometheus Metrics', 'prometheus'], 'category': 'Monitoring'},
 'Kibana Dashboard': {'html': ['Kibana Dashboard', 'kibana'], 'category': 'Monitoring'},
 'Elastic Search': {'html': ['Elastic Search', 'elasticsearch'], 'category': 'Search Engine'},
 'OpenSearch Dashboard': {'html': ['OpenSearch Dashboard', 'opensearch'], 'category': 'Search Engine'},
 'Apache Solr Admin': {'html': ['Apache Solr Admin', 'solr'], 'category': 'Search Engine'},
 'Apache Tomcat Manager': {'html': ['Apache Tomcat Manager', 'tomcat'], 'category': 'Web Server'},
 'Jenkins Blue Ocean': {'html': ['Jenkins Blue Ocean', 'jenkins'], 'category': 'CI / CD'},
 'GitLab Omnibus': {'html': ['GitLab Omnibus', 'gitlab'], 'category': 'DevOps'},
 'Gitea UI': {'html': ['Gitea UI', 'gitea'], 'category': 'DevOps'},
 'Rundeck Community': {'html': ['Rundeck Community', 'rundeck'], 'category': 'Automation'},
 'Portainer CE': {'html': ['Portainer CE', 'portainer'], 'category': 'Container Management'},
 'Kubernetes Dashboard': {'html': ['Kubernetes Dashboard', 'kubernetes'], 'category': 'Container Orchestration'},
 'SonarQube Server': {'html': ['SonarQube Server', 'sonarqube'], 'category': 'Code Quality'},
 'Jira Software': {'html': ['Jira Software', 'jira'], 'category': 'Project Management'},
 'Confluence Server': {'html': ['Confluence Server', 'confluence'], 'category': 'Project Management'},
 'Atlassian Crowd': {'html': ['Atlassian Crowd', 'atlassian'], 'category': 'Identity'},
 'Keycloak Admin': {'html': ['Keycloak Admin', 'keycloak'], 'category': 'Identity'},
 'Vault UI': {'html': ['Vault UI', 'vault'], 'category': 'Secrets Management'},
 'HashiCorp Consul': {'html': ['HashiCorp Consul', 'consul'], 'category': 'Service Discovery'},
 'HashiCorp Nomad': {'html': ['HashiCorp Nomad', 'nomad'], 'category': 'Service Discovery'},
 'HashiCorp Vault': {'html': ['HashiCorp Vault', 'vault'], 'category': 'Secrets Management'},
 'OpenAM': {'html': ['OpenAM', 'openam'], 'category': 'Identity'},
 'ForgeRock': {'html': ['ForgeRock', 'forgerock'], 'category': 'Identity'},
 'OpenDJ': {'html': ['OpenDJ', 'opendj'], 'category': 'Directory'},
 'Samba File Server': {'html': ['Samba File Server', 'samba'], 'category': 'File Sharing'},
 'CouchDB Fauxton': {'html': ['Fauxton', 'couchdb'], 'category': 'Database'},
 'OpenSearch Dashboards': {'html': ['OpenSearch Dashboards', 'opensearch'], 'category': 'Search Engine'},
 'Airflow UI': {'html': ['Airflow UI', 'airflow'], 'category': 'Data Platform'},
 'Apache Zeppelin': {'html': ['Apache Zeppelin', 'zeppelin'], 'category': 'Data Platform'},
 'TensorFlow Serving': {'html': ['TensorFlow Serving', 'tensorflow'], 'category': 'AI / ML'},
 'PyTorch Serve': {'html': ['PyTorch Serve', 'pytorch'], 'category': 'AI / ML'}}

for name, signature in EXTENDED_SIGNATURES.items():
    if name in SIGNATURES:
        current = SIGNATURES[name]
        current.update(signature)
        for key, value in signature.items():
            if key in {"html", "headers", "meta", "scripts", "cookies", "paths"}:
                existing = current.get(key)
                if isinstance(existing, list) and isinstance(value, list):
                    current[key] = existing + value
                elif isinstance(existing, dict) and isinstance(value, dict):
                    current[key] = {**existing, **value}
                else:
                    current[key] = value
        continue
    SIGNATURES[name] = signature

for name, signature in WEB_SERVER_SIGNATURES.items():
    if name not in SIGNATURES:
        SIGNATURES[name] = signature


def _compile_pattern(value: Any) -> Any:
    if isinstance(value, str):
        try:
            return re.compile(value, re.IGNORECASE)
        except re.error:
            return re.compile(re.escape(value), re.IGNORECASE)
    if isinstance(value, list):
        return [_compile_pattern(v) for v in value if isinstance(v, (str, re.Pattern))]
    if isinstance(value, dict):
        return {k: _compile_pattern(v) for k, v in value.items()}
    return value


def _extract_literals(pattern: str) -> set[str]:
    raw = pattern
    if not isinstance(raw, str):
        raw = str(raw)
    tokens = re.split(r"[^A-Za-z0-9_./-]", raw)
    return {token.lower() for token in tokens if len(token) >= 3}


def _compile_signature(signature: dict) -> dict:
    compiled = {}
    for key, value in signature.items():
        if key in {"headers", "cookies", "html", "scripts", "meta", "paths"}:
            compiled[key] = _compile_pattern(value)
        else:
            compiled[key] = value
    return compiled


COMPILED_SIGNATURES = {name: _compile_signature(sig) for name, sig in SIGNATURES.items()}

SIGNATURES_BY_HEADER: dict[str, list[str]] = {}
SIGNATURES_BY_META: dict[str, list[str]] = {}
SIGNATURES_BY_COOKIE_TOKEN: dict[str, list[str]] = {}
SIGNATURES_BY_SCRIPT_TOKEN: dict[str, list[str]] = {}
SIGNATURES_BY_HTML_TOKEN: dict[str, list[str]] = {}
SIGNATURES_BY_PATH_TOKEN: dict[str, list[str]] = {}

for name, sig in COMPILED_SIGNATURES.items():
    for header_name in sig.get("headers", {}):
        SIGNATURES_BY_HEADER.setdefault(header_name.lower(), []).append(name)
    for meta_name in sig.get("meta", {}):
        SIGNATURES_BY_META.setdefault(meta_name.lower(), []).append(name)
    for cookie_pattern in sig.get("cookies", []):
        for token in _extract_literals(cookie_pattern.pattern if hasattr(cookie_pattern, "pattern") else str(cookie_pattern)):
            SIGNATURES_BY_COOKIE_TOKEN.setdefault(token, []).append(name)
    for script_pattern in sig.get("scripts", []):
        for token in _extract_literals(script_pattern.pattern if hasattr(script_pattern, "pattern") else str(script_pattern)):
            SIGNATURES_BY_SCRIPT_TOKEN.setdefault(token, []).append(name)
    for html_pattern in sig.get("html", []):
        for token in _extract_literals(html_pattern.pattern if hasattr(html_pattern, "pattern") else str(html_pattern)):
            SIGNATURES_BY_HTML_TOKEN.setdefault(token, []).append(name)
    for path_pattern in sig.get("paths", []):
        for token in _extract_literals(path_pattern.pattern if hasattr(path_pattern, "pattern") else str(path_pattern)):
            SIGNATURES_BY_PATH_TOKEN.setdefault(token, []).append(name)
