"""Curated web-server and proxy signatures with protocol-level evidence."""

WEB_SERVER_SIGNATURES = {
    "Lighttpd": {"category": "Web Server", "headers": {"Server": r"lighttpd(?:/([\d.]+))?"}},
    "H2O": {"category": "Web Server", "headers": {"Server": r"h2o(?:/([\d.]+))?"}},
    "Tengine": {"category": "Web Server", "headers": {"Server": r"Tengine(?:/([\d.]+))?"}},
    "Mongoose": {"category": "Web Server", "headers": {"Server": r"Mongoose(?:/([\d.]+))?"}},
    "CivetWeb": {"category": "Web Server", "headers": {"Server": r"CivetWeb(?:/([\d.]+))?"}},
    "Abyss Web Server": {"category": "Web Server", "headers": {"Server": r"Abyss(?:/([\d.]+))?"}},
    "Xitami": {"category": "Web Server", "headers": {"Server": r"Xitami(?:/([\d.]+))?"}},
    "WebtoB": {"category": "Web Server", "headers": {"Server": r"WebtoB(?:/([\d.]+))?"}},
    "Resin": {"category": "Application Server", "headers": {"Server": r"Resin(?:/([\d.]+))?"}},
    "Undertow": {"category": "Application Server", "headers": {"Server": r"Undertow(?:/([\d.]+))?"}},
    "WildFly": {"category": "Application Server", "headers": {"Server": r"WildFly(?:/([\d.]+))?"}},
    "JBoss": {"category": "Application Server", "headers": {"Server": r"JBoss(?:/([\d.]+))?"}},
    "WebLogic": {"category": "Application Server", "headers": {"Server": r"WebLogic(?:/([\d.]+))?"}},
    "WebSphere": {"category": "Application Server", "headers": {"Server": r"WebSphere(?:/([\d.]+))?"}},
    "GlassFish": {"category": "Application Server", "headers": {"Server": r"GlassFish(?:/([\d.]+))?"}},
    "Payara": {"category": "Application Server", "headers": {"Server": r"Payara(?:/([\d.]+))?"}},
    "Vert.x": {"category": "Application Server", "headers": {"Server": r"Vert\.x(?:/([\d.]+))?"}},
    "Netty": {"category": "Application Server", "headers": {"Server": r"Netty(?:/([\d.]+))?"}},
    "uWSGI": {"category": "Application Server", "headers": {"Server": r"uWSGI(?:/([\d.]+))?"}},
    "Waitress": {"category": "Application Server", "headers": {"Server": r"waitress(?:/([\d.]+))?"}},
    "Hypercorn": {"category": "Application Server", "headers": {"Server": r"hypercorn(?:/([\d.]+))?"}},
    "Daphne": {"category": "Application Server", "headers": {"Server": r"daphne(?:/([\d.]+))?"}},
    "Kestrel": {"category": "Application Server", "headers": {"Server": r"Kestrel(?:/([\d.]+))?"}},
    "HttpSys": {"category": "Application Server", "headers": {"Server": r"Microsoft-HTTPAPI(?:/([\d.]+))?"}},
    "Puma": {"category": "Application Server", "headers": {"Server": r"Puma(?:/([\d.]+))?"}},
    "Unicorn": {"category": "Application Server", "headers": {"Server": r"Unicorn(?:/([\d.]+))?"}},
    "Passenger": {"category": "Application Server", "headers": {"Server": r"Phusion Passenger(?:/([\d.]+))?"}},
    "Thin": {"category": "Application Server", "headers": {"Server": r"thin(?:/([\d.]+))?"}},
    "WEBrick": {"category": "Application Server", "headers": {"Server": r"WEBrick(?:/([\d.]+))?"}},
    "Squid": {"category": "Proxy", "headers": {"Via": r"[^,]*squid(?:/([\d.]+))?"}},
    "Varnish": {"category": "Proxy", "headers": {"Via": r"[^,]*varnish(?:/([\d.]+))?"}},
    "Apache Traffic Server": {"category": "Proxy", "headers": {"Server": r"ATS(?:/([\d.]+))?"}},
    "Tinyproxy": {"category": "Proxy", "headers": {"Via": r"[^,]*tinyproxy(?:/([\d.]+))?"}},
    "Privoxy": {"category": "Proxy", "headers": {"Server": r"Privoxy(?:/([\d.]+))?"}},
    "mitmproxy": {"category": "Proxy", "headers": {"Server": r"mitmproxy(?:/([\d.]+))?"}},
    "Traefik": {"category": "Reverse Proxy", "headers": {"Server": r"Traefik(?:/([\d.]+))?"}},
    "Envoy Proxy": {"category": "Reverse Proxy", "headers": {"Server": r"envoy(?:/([\d.]+))?"}},
    "OpenResty Edge": {"category": "Reverse Proxy", "headers": {"Server": r"openresty(?:/([\d.]+))?"}, "excludes": ["OpenResty"]},
    "Node.js HTTP": {"category": "Application Server", "headers": {"X-Powered-By": r"Node\.js(?:/([\d.]+))?"}},
    "Bun HTTP": {"category": "Application Server", "headers": {"Server": r"Bun(?:/([\d.]+))?"}},
    "Deno Deploy": {"category": "Application Server", "headers": {"Server": r"Deno(?:/([\d.]+))?"}},
    "Warp": {"category": "Application Server", "headers": {"Server": r"warp(?:/([\d.]+))?"}},
}
